var { readFile } = require('fs').promises
var { parse, join } = require('path')

const alias = [
  { filter: /^react-native$/, path: './node_modules/react-native-web/dist/index.js' },
  {
    filter: /react-native-vector-icons\/MaterialCommunityIcons/,
    path: './node_modules/@expo/vector-icons/MaterialCommunityIcons.js',
  },
  {
    filter: /MaterialCommunityIcons.ttf/,
    path: './src/assets/materialdesignicons-light-webfont.ttf',
  },
]

module.exports = (conf) => {
  return {
    name: 'vector-icons',
    setup(build) {
      alias.forEach(({ filter, path }) => {
        build.onResolve({ filter }, (args) => ({
          path: join(process.cwd(), path),
        }))
      })
      build.onLoad(
        {
          filter: /@expo.*glyphmaps.*json/,
        },
        async (args) => {
          //console.log(args);
          let result = '{}'
          const iconSet = parse(args.path).name
          if (conf.hasOwnProperty(iconSet)) {
            const source = await readFile(args.path, 'utf8')
            const glyphmap = JSON.parse(source)
            result = Object.fromEntries(
              Object.entries(glyphmap)
                .filter(([name, icon]) => conf[iconSet].includes(name))
                .map(([name, icon]) => [name, icon - 0xf0000 + 0xf000])
            )

            //console.log(result);
          }
          return { contents: `export default ${JSON.stringify(result)}` }
        }
      )
    },
  }
}

//https://materialdesignicons.com/cdn/light/0.2.63/

const glyphmaps = [
  'AntDesign',
  'Entypo',
  'EvilIcons',
  'Feather',
  'FontAwesome',
  'FontAwesome5Free',
  'FontAwesome5Pro',
  'Fontisto',
  'Foundation',
  'Ionicons',
  'MaterialCommunityIcons',
  'MaterialIcons',
  'Octicons',
  'SimpleLineIcons',
  'Zocial',
]

const mdiLight = [
  'account',
  'alarm',
  'alarm-plus',
  'alert',
  'alert-circle',
  'alert-octagon',
  'arrange-bring-forward',
  'arrange-bring-to-front',
  'arrange-send-backward',
  'arrange-send-to-back',
  'arrow-down',
  'arrow-left',
  'arrow-right',
  'arrow-up',
  'bank',
  'flask',
  'flask-empty',
  'bell',
  'bell-off',
  'bluetooth',
  'book',
  'book-multiple',
  'bookmark',
  'border-all',
  'border-bottom',
  'border-horizontal',
  'border-inside',
  'border-left',
  'border-none',
  'border-outside',
  'border-right',
  'border-top',
  'border-vertical',
  'briefcase',
  'calendar',
  'camcorder',
  'camera',
  'cart',
  'chart-areaspline',
  'chart-bar',
  'chart-histogram',
  'chart-line',
  'chart-pie',
  'check',
  'chevron-double-down',
  'chevron-double-left',
  'chevron-double-right',
  'chevron-double-up',
  'chevron-down',
  'chevron-left',
  'chevron-right',
  'chevron-up',
  'clipboard',
  'clipboard-check',
  'clipboard-text',
  'clock',
  'closed-caption',
  'cloud',
  'cloud-download',
  'cloud-upload',
  'comment',
  'comment-alert',
  'comment-text',
  'console',
  'content-cut',
  'content-duplicate',
  'content-paste',
  'content-save',
  'content-save-all',
  'credit-card',
  'credit-card-scan',
  'crop',
  'crop-free',
  'currency-eur',
  'currency-gbp',
  'currency-rub',
  'currency-usd',
  'delete',
  'diamond-stone',
  'dots-horizontal',
  'dots-vertical',
  'download',
  'eject',
  'email',
  'email-open',
  'eye',
  'eye-off',
  'factory',
  'fast-forward',
  'file',
  'file-multiple',
  'flag',
  'flash',
  'folder',
  'folder-multiple',
  'folder-plus',
  'format-align-center',
  'format-align-justify',
  'format-align-left',
  'format-align-right',
  'format-bold',
  'format-clear',
  'format-float-center',
  'format-float-left',
  'format-float-none',
  'format-float-right',
  'format-indent-decrease',
  'format-indent-increase',
  'format-italic',
  'format-line-spacing',
  'format-list-bulleted',
  'format-list-numbers',
  'format-quote-close',
  'format-underline',
  'format-wrap-inline',
  'format-wrap-square',
  'format-wrap-tight',
  'format-wrap-top-bottom',
  'forum',
  'fullscreen',
  'fullscreen-exit',
  'gift',
  'grid',
  'grid-off',
  'group',
  'heart',
  'help',
  'help-circle',
  'hexagon',
  'home',
  'image',
  'information',
  'label',
  'layers',
  'lightbulb',
  'link',
  'link-variant',
  'lock',
  'lock-open',
  'login',
  'logout',
  'magnify',
  'magnify-minus',
  'magnify-plus',
  'map-marker',
  'memory',
  'menu',
  'message',
  'message-alert',
  'message-image',
  'message-processing',
  'message-reply',
  'message-text',
  'message-video',
  'microphone',
  'microphone-off',
  'minus',
  'minus-box',
  'minus-circle',
  'monitor',
  'monitor-multiple',
  'nfc-variant',
  'note',
  'note-plus',
  'note-text',
  'octagon',
  'paperclip',
  'pause',
  'pencil',
  'phone',
  'pin',
  'pin-off',
  'play',
  'plus',
  'plus-box',
  'plus-circle',
  'power',
  'presentation',
  'presentation-play',
  'printer',
  'redo-variant',
  'refresh',
  'repeat',
  'repeat-off',
  'repeat-once',
  'rewind',
  'rss',
  'script',
  'settings',
  'shield',
  'shuffle',
  'signal',
  'sitemap',
  'skip-next',
  'skip-previous',
  'sleep',
  'sleep-off',
  'spellcheck',
  'star',
  'star-half',
  'stop',
  'tab',
  'table',
  'tag',
  'television',
  'thumb-down',
  'thumb-up',
  'thumbs-up-down',
  'tooltip',
  'tooltip-text',
  'triangle',
  'trophy',
  'undo-variant',
  'unfold-less-horizontal',
  'unfold-more-horizontal',
  'ungroup',
  'upload',
  'vector-arrange-above',
  'vector-arrange-below',
  'vector-combine',
  'vector-difference',
  'vector-difference-ab',
  'vector-difference-ba',
  'vector-intersection',
  'vector-union',
  'view-dashboard',
  'view-module',
  'volume-high',
  'volume-off',
  'wifi',
  'xml',
  'book-plus',
  'hamburger',
  'inbox',
  'note-multiple',
  'heart-half',
  'lightbulb-on',
  'rhombus',
  'cancel',
  'clipboard-plus',
  'file-plus',
  'format-align-bottom',
  'format-align-middle',
  'format-align-top',
  'format-list-checks',
  'format-quote-open',
  'grid-large',
  'heart-off',
  'music',
  'music-off',
  'tab-plus',
  'volume-plus',
  'volume-minus',
  'volume-mute',
  'unfold-less-vertical',
  'unfold-more-vertical',
  'taco',
  'square',
  'circle',
  'arrow-down-circle',
  'arrow-left-circle',
  'arrow-right-circle',
  'arrow-up-circle',
]
